### ISSUE TITLE
Table doesn't show which is the default version of perl when multiple are available

### ISSUE THREAD

**Issue by nieder** [briandfoy/mac-perl-versions#2]
For example, on macOS 11.2, we have

https://github.com/briandfoy/mac-perl-versions/blob/50d7329b6fff0abc042e2b143f8aab3f678a098f/mac-perl-versions.json#L241-L243

/usr/bin/perl points to /usr/bin/perl5.28 (which is 5.28.2). It would be nice to have that extra bit of information available. That bit seems availble from the apple-oss-distro github, but you have to dig for it:

https://github.com/apple-oss-distributions/perl/blob/5a082ddcf9330b7089d701d51f5d45fb8bc1b820/Platforms/MacOSX/Makefile.inc#L1-L4
```
DEFAULT = 5.28
KNOWNVERSIONS = 5.18 5.28
BOOTSTRAPPERL = 5.30
EXTRAVERSIONERFLAGS = -DFORCE_TWO_NUMBER_VERSIONS
```

**Comment by briandfoy** [comment]
That looks like a good idea. I'll work on it soon.

**Comment by briandfoy** [comment]
I've updated the JSON to show the default versions. Thanks,

**Comment by nieder** [comment]
Awesome. Thank you. I work with the Fink project and we're always struggling to figure out what new version of perl Apple added on releases, so this list will help us quite a bit.
